
spring.application.name=api-gateway
server.port=8690

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.server.webflux.routes[0].id=address-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://address-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/address/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=CircuitBreaker=name=addressCircuitBreaker,fallbackUri=forward:/fallback/address

spring.cloud.gateway.server.webflux.routes[1].id=department-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://department-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/department/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=CircuitBreaker=name=departmentCircuitBreaker,fallbackUri=forward:/fallback/department

spring.cloud.gateway.server.webflux.routes[2].id=employee-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://employee-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/employee/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=CircuitBreaker=name=employeeCircuitBreaker,fallbackUri=forward:/fallback/employee

resilience4j.circuitbreaker.instances.addressCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.addressCircuitBreaker.slidingWindowSize=3
resilience4j.circuitbreaker.instances.addressCircuitBreaker.minimumNumberOfCalls=2
resilience4j.circuitbreaker.instances.addressCircuitBreaker.failureRateThreshold=3
resilience4j.circuitbreaker.instances.addressCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.addressCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.addressCircuitBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.circuitbreaker.instances.departmentCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.departmentCircuitBreaker.slidingWindowSize=3
resilience4j.circuitbreaker.instances.departmentCircuitBreaker.minimumNumberOfCalls=2
resilience4j.circuitbreaker.instances.departmentCircuitBreaker.failureRateThreshold=3
resilience4j.circuitbreaker.instances.departmentCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.departmentCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.departmentCircuitBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.circuitbreaker.instances.employeeCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.employeeCircuitBreaker.slidingWindowSize=3
resilience4j.circuitbreaker.instances.employeeCircuitBreaker.minimumNumberOfCalls=2
resilience4j.circuitbreaker.instances.employeeCircuitBreaker.failureRateThreshold=3
resilience4j.circuitbreaker.instances.employeeCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.employeeCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.employeeCircuitBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true

#Actuator Properties
#http://localhost:8690/actuator (show all endpoints of actuator)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
