spring.application.name=eureka-service
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
server.port= 8761

#http://localhost:8690/actuator (show all endpoints of actuator)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
